### ISSUE TITLE
PNG delivery is broken

### ISSUE THREAD

**Issue by th-we** [Edirom/SMuFL-Browser#3]
Some glyphs only render as transparent images for me, e.g. this one:

https://smufl-browser.edirom.de/E540.png

Did something break?

**Comment by peterstadler** [comment]
Thanks for the bug report; and sorry: I noticed only today …

At first I thought it to be a deployment issue but then I realized, that the Docker image indeed features the defect images. Turns out to be a rather annoying bug in @aerhard's otf2png converter (introduced by some Java upgrade?) which fails to render some images—but not all—correctly. 
Since my Java foo is not that strong I'm now looking into replacing this piece of code with some other implementation.

**Comment by peterstadler** [comment]
After fiddling with reimplementing the image extraction in Python (results were poorer than the nice otf2png by @aerhard) I took another look at the build process. Turns out an update to OpenJDK9 fixes the issue.
